[0m[[0m[31merror[0m] [0m[0morg.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://10.10.30.192:8983/solr/applies: Async exception during distributed update: Error from server at http://10.10.30.189:8983/solr/applies_shard1_replica_n1/: null[0m
[0m[[0m[31merror[0m] [0m[0m[0m
[0m[[0m[31merror[0m] [0m[0m[0m
[0m[[0m[31merror[0m] [0m[0m[0m
[0m[[0m[31merror[0m] [0m[0mrequest: http://10.10.30.189:8983/solr/applies_shard1_replica_n1/[0m
[0m[[0m[31merror[0m] [0m[0mRemote error message: ERROR: [doc=999999] Error adding field 'date'='2022-01-03 00:00:00.000,' msg=Invalid Date String:'2022-01-03 00:00:00.000,'[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:665)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:265)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:248)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:211)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:177)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:138)[0m
[0m[[0m[31merror[0m] [0m[0m	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:156)[0m
[0m[[0m[31merror[0m] [0m[0m	at com.github.takezoe.solr.scala.BatchRegister.add$$anonfun$1(BatchRegister.scala:18)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)[0m
[0m[[0m[31merror[0m] [0m[0m	at com.github.takezoe.solr.scala.BatchRegister.add(BatchRegister.scala:19)[0m
[0m[[0m[31merror[0m] [0m[0m	at com.github.takezoe.solr.scala.BatchRegister.<init>(BatchRegister.scala:8)[0m
[0m[[0m[31merror[0m] [0m[0m	at com.github.takezoe.solr.scala.SolrClient.add(SolrClient.scala:117)[0m
[0m[[0m[31merror[0m] [0m[0m	at Main$package$.run(Main.scala:16)[0m
[0m[[0m[31merror[0m] [0m[0m	at run.main(Main.scala:3)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.reflect.Method.invoke(Method.java:566)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.invokeMain(Run.scala:143)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.execute$1(Run.scala:93)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$.executeSuccess(Run.scala:186)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.runWithLoader(Run.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1983)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1922)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:213)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:829)[0m
[0m[[0m[31merror[0m] [0m[0m(Compile / [31mrun[0m) org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://10.10.30.192:8983/solr/applies: Async exception during distributed update: Error from server at http://10.10.30.189:8983/solr/applies_shard1_replica_n1/: null[0m
[0m[[0m[31merror[0m] [0m[0m[0m
[0m[[0m[31merror[0m] [0m[0m[0m
[0m[[0m[31merror[0m] [0m[0m[0m
[0m[[0m[31merror[0m] [0m[0mrequest: http://10.10.30.189:8983/solr/applies_shard1_replica_n1/[0m
[0m[[0m[31merror[0m] [0m[0mRemote error message: ERROR: [doc=999999] Error adding field 'date'='2022-01-03 00:00:00.000,' msg=Invalid Date String:'2022-01-03 00:00:00.000,'[0m
